package my.converter;

/**
 *
 * @author MAYANK
 */
public class currency extends javax.swing.JFrame {

    /**
     * Creates new form currency
     */
    public currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        box1 = new javax.swing.JComboBox<>();
        box2 = new javax.swing.JComboBox<>();
        value1 = new javax.swing.JLabel();
        valueenter = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        textresult = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        Title.setText("Currency Converter");
        Title.setToolTipText("");

        text1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text1.setText("Select Currency 1");

        text2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text2.setText("Select Currency 2");

        box1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        box1.setMaximumRowCount(5);
        box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rupees", "US Dollar", "Euro", "Japanese Yen ", "Pound sterling", "Canadian Dollar", "Swiss franc", "Australian Dollar", "Chinese yuan", "Swedish Krona", "New Zealand Dollar" }));
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rupees", "US Dollar", "Euro", "Japanese Yen ", "Pound sterling", "Canadian Dollar", "Swiss franc", "Australian Dollar", "Chinese yuan", "Swedish Krona", "New Zealand Dollar" }));
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        value1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        value1.setText("Values");

        valueenter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valueenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueenterActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        result.setText("Result");

        convert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        convert.setText("Convert");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box1, 0, 175, Short.MAX_VALUE)
                            .addComponent(box2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(value1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valueenter)
                    .addComponent(textresult, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convert, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(value1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueenter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textresult)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_box1ActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        String x = box1.getSelectedItem().toString();
        String y = box2.getSelectedItem().toString();
        String a1=valueenter.getText();
        Double a2=Double.parseDouble(a1);
        Double a3;
        if(x==y)
        {
            a3=a2;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="US Dollar")
        {
            a3=a2/64.56;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Euro")
        {
            a3=a2*0.015;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Japanese Yen")
        {
            a3=a2*1.72;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Pound sterling")
        {
            a3=a2*0.012;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Canadian Dollar")
        {
            a3=a2*0.021;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Swiss franc")
        {
            a3=a2*0.016;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Australian Dollar")
        {
            a3=a2*0.021;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Indian Rupees"&&y=="Chinese yuan")
        {
            a3=a2*0.11;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Indian Rupees")
        {
            a3=a2*64.56;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Euro")
        {
            a3=a2*0.94;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Pound sterling")
        {
            a3=a2*0.94;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Japanese Yen")
        {
            a3=a2*110.83;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Canadian Dollar")
        {
            a3=a2*1.34;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Swiss franc")
        {
            a3=a2*1.01;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Australian Dollar")
        {
            a3=a2*1.33;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="US Dollar"&&y=="Chinese yuan")
        {
            a3=a2*6.90;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Indian Rupees")
        {
            a3=a2*68.89;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="US Dollar")
        {
            a3=a2*1.07;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Japanese Yen")
        {
            a3=a2*118.26;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Pound sterling")
        {
            a3=a2*0.86;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Canadian Dollar")
        {
            a3=a2*1.42;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Swiss franc")
        {
            a3=a2*1.07;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Australian Dollar")
        {
            a3=a2*1.41;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Euro"&&y=="Chinese yuan")
        {
            a3=a2*7.32;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Indian Rupees")
        {
            a3=a2*0.58;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="US Dollar")
        {
            a3=a2*0.0090;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Euro")
        {
            a3=a2*0.0085;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Pound sterling")
        {
            a3=a2*0.0072;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Canadian Dollar")
        {
            a3=a2*0.012;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Swiss franc")
        {
            a3=a2*0.0091;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Australian Dollar")
        {
            a3=a2*0.012;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Japanese Yen"&&y=="Chinese yuan")
        {
            a3=a2*0.063;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Pound sterling"&&y=="Indian Rupees")
        {
            a3=a2*80.53;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Pound sterling"&&y=="US Dollar")
        {
            a3=a2*1.25;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Pound sterling"&&y=="Japanese Yen")
        {
            a3=a2*138.23;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Pound sterling"&&y=="Euro")
        {
            a3=a2*1.17;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Pound sterling"&&y=="Canadian Dollar")
        {
            a3=a2*1.66;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        } 
        else if(x=="Pound sterling"&&y=="Swiss franc")
        {
            a3=a2*1.25;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }    
        else if(x=="Pound sterling"&&y=="Australian Dollar")
        {
            a3=a2*1.66;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        } 
        else if(x=="Pound sterling"&&y=="Chinese yuan")
        {
            a3=a2*8.61;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        } 
        else if(x=="Canadian Dollar"&&y=="Indian Rupees")
        {
            a3=a2*48.06;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }        
        else if(x=="Canadian Dollar"&&y=="US Dollar")
        {
            a3=a2*0.74;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }        
        else if(x=="Canadian Dollar"&&y=="Japanese Yen")
        {
            a3=a2*82.56;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }        
        else if(x=="Canadian Dollar"&&y=="Euro")
        {
            a3=a2*0.70;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }        
        else if(x=="Canadian Dollar"&&y=="Pound sterling")
        {
            a3=a2*0.60;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Canadian Dollar"&&y=="Swiss franc")
        {
            a3=a2*0.75;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Canadian Dollar"&&y=="Australian Dollar")
        {
            a3=a2*1.0;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Canadian Dollar"&&y=="Chinese yuan")
        {
            a3=a2*5.18;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Indian Rupees")
        {
            a3=a2*63.89;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="US Dollar")
        {
            a3=a2*0.99;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Euro")
        {
            a3=a2*0.94;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Japanese Yen")
        {
            a3=a2*110.02;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Pound sterling")
        {
            a3=a2*0.80;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Canadian Dollar")
        {
            a3=a2*1.33;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Australian Dollar")
        {
            a3=a2*1.32;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Swiss franc"&&y=="Chinese yuan")
        {
            a3=a2*6.85;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Indian Rupees")
        {
            a3=a2*48.51;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="US Dollar")
        {
            a3=a2*0.75;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Euro")
        {
            a3=a2*0.71;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Japanese Yen")
        {
            a3=a2*82.31;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Pound sterling")
        {
            a3=a2*0.60;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Canadian Dollar")
        {
            a3=a2*1.0;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Swiss franc")
        {
            a3=a2*0.76;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Australian Dollar"&&y=="Chinese yuan")
        {
            a3=a2*5.18;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan"&&y=="Indian Rupees")
        {
            a3=a2*9.37;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="US Dollar")
        {
            a3=a2*0.14;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Euro")
        {
            a3=a2*0.14;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Japanese Yen")
        {
            a3=a2*15.91;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Pound sterling")
        {
            a3=a2*0.12;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Canadian Dollar")
        {
            a3=a2*0.19;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Swiss franc")
        {
            a3=a2*0.15;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
        else if(x=="Chinese yuan "&&y=="Australian Dollar")
        {
            a3=a2*0.19;
            a3= (double)Math.round(a3*10000.0) / 10000.0;
            String a4=Double.toString(a3);
            textresult.setText(a4);
        }
    }//GEN-LAST:event_convertActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        textresult.setText("");
        valueenter.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2ActionPerformed

    private void valueenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueenterActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JButton convert;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel result;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JTextField textresult;
    private javax.swing.JLabel value1;
    private javax.swing.JTextField valueenter;
    // End of variables declaration//GEN-END:variables
}
